#Configuração de rotas
/portal:  PortalController
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController

#projeto de Vicente
/listar-produtos: ListarProdutosController
/adicionar-produto-form:  AdicionarProdutoFormController
/adicionar-produto: AdicionarProdutoController
/apagar-produto:  ApagarProdutoController
/editar-produto-form: EditarProdutoFormController
/editar-produto:  EditarProdutoController
/404found:  path404Controller

#FuncoesSecretarios
/opcoes: opcoesAdminController
/listar-funcionarios: ListarFuncionariosController
/listar-func: listarController
/adcionar-funcionario: adcionarFuncionarioController
/adcionar-funcionario-form: adcionarFuncionarioFormController
/editar-funcionario-form: editarFuncionarioFormController
/editar-funcionario:  EditarFuncionarioController
/apagar-funcionario:  ApagaFuncionarioController
/listar-medicamento: listarMedicamentoController
/adcionar-medicamento: adcionarMedicamentoController
/adcionar-medicamento-form: adcionarMedicamentoFormController
/editar-medicamento-form: editarMedicamentoFormController
/editar-medicamento:  EditarMedicamentoController
/apagar-medicamento: ApagarMedicamentoController
/adcionar-ubs: AdcionarUbsController
/adcionar-ubs-form: adcionarUbsFormController
/listar-ubs: listarUbsController
/editar-ubs-form: editarUbsFormController
/editar-ubs:  EditarUbsController
/apagar-ubs:  ApagaUbsController

#funcoes Acs
/opcoesAcs: opcoesAcsController
/adcionar-familia: AdcionarFamiliaController
/adcionar-familia-form: adcionarFamiliaFormController
/listar-familia: listarFamiliaController
/editar-familia-form: editarFamiliaFormController
/editar-familia:  EditarFamiliaController
/apagar-familia: ApagarFamiliaController
/adcionar-paciente: AdcionarPacienteController
/adcionar-paciente-form: AdcionarPacienteFormController
/listar-paciente: listarPacienteController
/apagar-paciente: ApagaPacienteController
/editar-paciente-form: editarPacienteFormController
/editar-paciente:  EditarPacienteController

#funções Atendente
/opcoesAtendente: opcoesAtendenteControler
/agendar: AgendaController
/BuscaAjax: BuscaController
/consulta: consultaController
/adcionarConsulta: adcionarConsultaController
/marcarConsulta: marcarConsultaController
/listar-medico: listarMedicoController
/MarcarConsulta: marcarConsultaFormController
/Marcar-Consulta: marcarConsultaEstruturaController
/EnvioAjax: EnvioController
/editar-consulta-form: editarConsultaFormController
/editar-consulta:  EditarConsultaController
/desmarcar-consulta-form: desmarcarConsultaController

#funcoes Medico
/opcoesMedico: opcoesMedicoController
/agendarPorMedico: AgendaMedicoController
/BuscaMedico: BuscaMedicoController
/editar-prontuario-form: editarProntuarioFormController
/editar-prontuario: EditarProntuarioController
/listar-prontuario: listarProntuarioController
/listar-pacienteProntuario: listarPacienteProntuarioController
/exibir-historico-consulta: historioConsultaController
/listar-exames: listarExamesController
/listar-avaliacao: listarAvaliacaoController
/listar-encaminhamento: listarEncaminhamentoController
